import { useState } from 'react'
import { Activity, BatteryCharging, Gauge, SlidersHorizontal, Zap } from 'lucide-react'
import { siteConfig } from '../data/siteConfig'
import { DiagramRenderer } from './PhysicsDiagrams'
import { AlertBox, ConceptCard, FormulaBox, SectionShell } from './ui'
const fmt = (v, d=2) => Math.abs(v) >= 10000 || Math.abs(v) < 0.01 ? v.toExponential(2) : Number(v.toFixed(d)).toString()
function Slider({ label, value, min, max, step = 1, unit = '', onChange }) { return <label className="rounded-2xl bg-slate-50 p-4 dark:bg-white/[.045]"><div className="mb-3 flex items-center justify-between gap-3"><span className="text-xs font-black uppercase tracking-[.14em] text-slate-500 dark:text-slate-400">{label}</span><strong className="font-mono text-sm text-ink dark:text-white">{value}{unit}</strong></div><input className="range-control" type="range" min={min} max={max} step={step} value={value} onChange={(e) => onChange(Number(e.target.value))} /></label> }
function Card({ title, icon: Icon = Activity, children, explanation, insight, ask }) { return <article className="glass-card overflow-hidden"><div className="border-b border-slate-200 bg-white/80 p-5 dark:border-white/10 dark:bg-white/[.04] md:p-6"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-amber-100 text-amber-800 dark:bg-amber-300/12 dark:text-amber-200"><Icon size={20} /></span><h3 className="text-xl font-black tracking-tight text-ink dark:text-white">{title}</h3></div></div><div className="grid gap-5 p-5 md:p-6">{children}<p className="text-sm font-semibold leading-7 text-slate-600 dark:text-slate-300">{explanation}</p><div className="grid gap-4 lg:grid-cols-2"><AlertBox title="Exam insight" tone="meaning">{insight}</AlertBox><AlertBox title="What NEET/JEE can ask" tone="neet">{ask}</AlertBox></div></div></article> }
export default function Simulations() { const sims = siteConfig.chapterNumber === 9 ? <Ch9 /> : siteConfig.chapterNumber === 10 ? <Ch10 /> : siteConfig.chapterNumber === 11 ? <Ch11 /> : <Ch12 />; return <SectionShell id="simulations" eyebrow="Interactive simulation lab" title={'Eight frontend-only ' + siteConfig.shortName + ' simulations.'} description="All simulations use local React state and SVG math. No paid API, backend, database or external asset is required." tone="tint">{sims}<div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><ConceptCard icon={SlidersHorizontal} kicker="Controls" title="Student-friendly sliders" color="blue">Every simulator exposes the quantities a student changes in exam problems.</ConceptCard><ConceptCard icon={Gauge} kicker="Outputs" title="Numerical feedback" color="teal">Live outputs update with formulas and diagrams.</ConceptCard><ConceptCard icon={Zap} kicker="Exam angle" title="NEET/JEE boxes" color="orange">Every simulation includes exam-facing takeaways.</ConceptCard><ConceptCard icon={BatteryCharging} kicker="Free" title="Frontend only" color="amber">No backend, paid API or database is used.</ConceptCard></div></SectionShell> }
function Ch9(){return <div className="grid gap-6"><LensFormula/><MirrorFormula/><LensPower/><PrismDeviation/><CriticalAngle/><Magnifier/><Microscope/><Telescope/></div>}
function LensFormula(){const[u,setU]=useState(-30),[f,setF]=useState(15); const v=1/(1/f+1/u); return <Card title="Lens Formula Explorer" explanation="Lens formula links object distance, image distance and focal length with sign convention." insight="Use Cartesian sign convention before substitution." ask="Image position, nature and magnification."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="u" value={u} min={-100} max={-10} unit=" cm" onChange={setU}/><Slider label="f" value={f} min={5} max={50} unit=" cm" onChange={setF}/><FormulaBox title="Output">v = {fmt(v)} cm</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="lens-ray"/></div></div></Card>}
function MirrorFormula(){const[u,setU]=useState(-40),[f,setF]=useState(-20); const v=1/(1/f-1/u); return <Card title="Mirror Formula Explorer" explanation="Mirror problems are sign-convention problems first, formula problems second." insight="Concave mirror has negative focal length in Cartesian convention." ask="Boards and NEET love image nature and magnification."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="u" value={u} min={-100} max={-10} unit=" cm" onChange={setU}/><Slider label="f" value={f} min={-50} max={-5} unit=" cm" onChange={setF}/><FormulaBox title="Output">v = {fmt(v)} cm</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="mirror"/></div></div></Card>}
function LensPower(){const[f,setF]=useState(25); const p=100/f; return <Card title="Lens Power Calculator" explanation="Power is reciprocal of focal length in metres." insight="Centimetres must be converted to metres." ask="Direct P=1/f and lens combinations."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="f" value={f} min={5} max={100} unit=" cm" onChange={setF}/><FormulaBox title="Output">P = {fmt(p)} D</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="lens-power"/></div></div></Card>}
function PrismDeviation(){const[a,setA]=useState(60),[mu,setMu]=useState(1.5); const dm=(mu-1)*a; return <Card title="Prism Minimum Deviation" explanation="For small-angle prism, deviation is approximately (mu-1)A." insight="Violet deviates more than red in normal dispersion." ask="Prism formula and dispersion order."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="A" value={a} min={20} max={80} unit=" deg" onChange={setA}/><Slider label="mu" value={mu} min={1.1} max={2} step={0.01} onChange={setMu}/><FormulaBox title="Output">delta ≈ {fmt(dm)} deg</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="prism-dispersion"/></div></div></Card>}
function CriticalAngle(){const[n,setN]=useState(1.5); const c=Math.asin(1/n)*180/Math.PI; return <Card title="Critical Angle Explorer" explanation="Total internal reflection starts when incidence angle exceeds critical angle." insight="Only denser-to-rarer travel can show TIR." ask="Optical fibre and critical angle."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="n denser" value={n} min={1.1} max={2.5} step={0.01} onChange={setN}/><FormulaBox title="Output">C = {fmt(c)} deg</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="reflection"/></div></div></Card>}
function Magnifier(){const[f,setF]=useState(10); return <Card title="Simple Microscope Magnification" explanation="Magnifying power is roughly 1+D/f for near point viewing." insight="Use D=25 cm for standard eye." ask="Direct magnifier questions."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="f" value={f} min={2} max={25} unit=" cm" onChange={setF}/><FormulaBox title="Output">M = {fmt(1+25/f)}</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="lens"/></div></div></Card>}
function Microscope(){return <Card title="Compound Microscope Visual" explanation="Objective forms enlarged real image; eyepiece acts as magnifier." insight="Short focal length objective improves magnification." ask="Ray diagram and magnifying power."><div className="visual-panel"><DiagramRenderer type="microscope"/></div></Card>}
function Telescope(){return <Card title="Astronomical Telescope Visual" explanation="Objective gathers light; eyepiece magnifies the image." insight="Magnifying power is fo/fe in normal adjustment." ask="Telescope formula and tube length."><div className="visual-panel"><DiagramRenderer type="telescope"/></div></Card>}
function Ch10(){return <div className="grid gap-6"><FringeWidth/><PathDiff/><DiffractionWidth/><Malus/><Brewster/><WavefrontSim/><Coherence/><ResolvingPower/></div>}
function FringeWidth(){const[l,setL]=useState(600),[D,setD]=useState(1),[d,setd]=useState(0.5); const beta=l*1e-9*D/(d*1e-3); return <Card title="YDSE Fringe Width" explanation="Fringe width increases with wavelength and screen distance, decreases with slit separation." insight="Use SI units carefully." ask="Direct beta=lambda D/d."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="lambda" value={l} min={400} max={700} unit=" nm" onChange={setL}/><Slider label="D" value={D} min={1} max={5} unit=" m" onChange={setD}/><Slider label="d" value={d} min={0.1} max={2} step={0.1} unit=" mm" onChange={setd}/><FormulaBox title="Output">beta = {fmt(beta*1000)} mm</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="ydse-interference"/></div></div></Card>}
function PathDiff(){const[n,setN]=useState(2),[l,setL]=useState(600); return <Card title="Bright Fringe Path Difference" explanation="Constructive interference occurs when path difference is n lambda." insight="Dark fringe uses (2n+1)lambda/2." ask="Fringe order questions."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="n" value={n} min={0} max={10} onChange={setN}/><Slider label="lambda" value={l} min={400} max={700} unit=" nm" onChange={setL}/><FormulaBox title="Output">Delta x = {fmt(n*l)} nm</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="fringe"/></div></div></Card>}
function DiffractionWidth(){const[l,setL]=useState(600),[D,setD]=useState(1),[a,setA]=useState(0.2); const w=2*l*1e-9*D/(a*1e-3); return <Card title="Single-Slit Central Maximum" explanation="Central maximum width is 2 lambda D/a." insight="Narrower slit gives wider diffraction." ask="Diffraction versus interference distinction."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="lambda" value={l} min={400} max={700} unit=" nm" onChange={setL}/><Slider label="D" value={D} min={1} max={5} unit=" m" onChange={setD}/><Slider label="a" value={a} min={0.1} max={1} step={0.1} unit=" mm" onChange={setA}/><FormulaBox title="Output">width = {fmt(w*1000)} mm</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="diffraction"/></div></div></Card>}
function Malus(){const[ang,setAng]=useState(45); const ratio=Math.cos(ang*Math.PI/180)**2; return <Card title="Malus Law Explorer" explanation="Intensity after analyzer follows I=I0 cos^2 theta." insight="At 90 degrees, ideal transmission is zero." ask="Polarization proves transverse nature."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="theta" value={ang} min={0} max={90} unit=" deg" onChange={setAng}/><FormulaBox title="Output">I/I0 = {fmt(ratio)}</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="polarization"/></div></div></Card>}
function Brewster(){const[n,setN]=useState(1.5); return <Card title="Brewster Angle" explanation="At Brewster angle, reflected light is plane polarized." insight="tan iB = mu." ask="Direct Brewster law."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="mu" value={n} min={1.1} max={2} step={0.01} onChange={setN}/><FormulaBox title="Output">iB = {fmt(Math.atan(n)*180/Math.PI)} deg</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="polarization"/></div></div></Card>}
function WavefrontSim(){return <Card title="Huygens Wavefront Visual" explanation="Every point on a wavefront acts as a source of secondary wavelets." insight="Rays are normal to wavefronts." ask="Reflection/refraction from Huygens principle."><div className="visual-panel"><DiagramRenderer type="wavefront"/></div></Card>}
function Coherence(){return <Card title="Coherent Sources Concept" explanation="Stable interference requires constant phase difference." insight="Two independent lamps do not give sustained fringes." ask="NCERT statement-based questions."><div className="visual-panel"><DiagramRenderer type="interference"/></div></Card>}
function ResolvingPower(){return <Card title="Resolving Power Visual" explanation="Resolution improves with larger aperture and smaller wavelength." insight="Diffraction limits optical instruments." ask="Conceptual JEE foundation."><div className="visual-panel"><DiagramRenderer type="diffraction-graph"/></div></Card>}
function Ch11(){return <div className="grid gap-6"><PhotoelectricEq/><StoppingPotential/><Threshold/><DeBroglie/><ElectronVoltage/><PhotonEnergy/><Davisson/><WaveParticle/></div>}
function PhotoelectricEq(){const[f,setF]=useState(8),[phi,setPhi]=useState(2); const k=4.136e-15*f*1e14-phi; return <Card title="Photoelectric Equation" explanation="Photoelectron kinetic energy depends on frequency, not intensity." insight="No emission below threshold frequency." ask="Einstein equation and graph slope h."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="f" value={f} min={3} max={12} unit=" x10^14 Hz" onChange={setF}/><Slider label="phi" value={phi} min={1} max={5} step={0.1} unit=" eV" onChange={setPhi}/><FormulaBox title="Output">Kmax = {fmt(Math.max(0,k))} eV</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="photoelectric-graph"/></div></div></Card>}
function StoppingPotential(){const[k,setK]=useState(2); return <Card title="Stopping Potential" explanation="Stopping potential measures maximum kinetic energy per charge." insight="eV0 = Kmax." ask="Stopping potential versus frequency graph."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="Kmax" value={k} min={0} max={10} step={0.1} unit=" eV" onChange={setK}/><FormulaBox title="Output">V0 = {fmt(k)} V</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="stopping-graph"/></div></div></Card>}
function Threshold(){return <Card title="Threshold Frequency Visual" explanation="Below threshold frequency, increasing intensity still cannot eject electrons." insight="Intensity changes photocurrent, frequency changes energy." ask="Most common NEET trap."><div className="visual-panel"><DiagramRenderer type="threshold"/></div></Card>}
function DeBroglie(){const[p,setP]=useState(5); const lambda=6.626e-34/(p*1e-24); return <Card title="de Broglie Wavelength" explanation="Matter waves have wavelength h/p." insight="Higher momentum means smaller wavelength." ask="Electron wavelength direct questions."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="p" value={p} min={1} max={20} unit=" x10^-24 kg m/s" onChange={setP}/><FormulaBox title="Output">lambda = {fmt(lambda)} m</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="de-broglie"/></div></div></Card>}
function ElectronVoltage(){const[V,setV]=useState(100); const lambda=1.227/Math.sqrt(V); return <Card title="Electron Wavelength by Voltage" explanation="For non-relativistic electrons, lambda in nm is about 1.227/sqrt(V)." insight="Accelerating voltage increases momentum." ask="JEE Main numerical favourite."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="V" value={V} min={1} max={1000} unit=" V" onChange={setV}/><FormulaBox title="Output">lambda = {fmt(lambda)} nm</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="matter-wave"/></div></div></Card>}
function PhotonEnergy(){const[l,setL]=useState(600); const e=1240/l; return <Card title="Photon Energy Calculator" explanation="Photon energy equals hc/lambda." insight="Shorter wavelength has higher energy." ask="Photoelectric and spectrum questions."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="lambda" value={l} min={200} max={900} unit=" nm" onChange={setL}/><FormulaBox title="Output">E = {fmt(e)} eV</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="photoelectric"/></div></div></Card>}
function Davisson(){return <Card title="Davisson-Germer Concept" explanation="Electron diffraction confirms wave nature of matter." insight="Bragg condition connects matter waves with crystal diffraction." ask="NCERT experiment statement."><div className="visual-panel"><DiagramRenderer type="davisson"/></div></Card>}
function WaveParticle(){return <Card title="Wave-Particle Duality Dashboard" explanation="Radiation and matter show particle and wave aspects depending on experiment." insight="Photoelectric effect supports particle nature; diffraction supports wave nature." ask="Assertion-reason favourite."><div className="visual-panel"><DiagramRenderer type="matter-wave"/></div></Card>}
function Ch12(){return <div className="grid gap-6"><BohrRadius/><BohrEnergy/><PhotonTransition/><Rydberg/><SeriesLimit/><Ionization/><AngularMomentum/><SpectrumLines/></div>}
function BohrRadius(){const[n,setN]=useState(2); return <Card title="Bohr Radius Explorer" explanation="Hydrogen orbit radius varies as n squared." insight="Higher orbits are farther apart." ask="rn=n^2 a0."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="n" value={n} min={1} max={8} onChange={setN}/><FormulaBox title="Output">r = {fmt(n*n*0.529)} angstrom</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="bohr-orbit"/></div></div></Card>}
function BohrEnergy(){const[n,setN]=useState(2); return <Card title="Hydrogen Energy Level" explanation="Hydrogen energy is negative and varies as -13.6/n^2 eV." insight="Energy approaches zero at ionization." ask="Direct energy level numerical."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="n" value={n} min={1} max={8} onChange={setN}/><FormulaBox title="Output">E_n = {fmt(-13.6/(n*n))} eV</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="energy-level"/></div></div></Card>}
function PhotonTransition(){const[ni,setNi]=useState(3),[nf,setNf]=useState(2); const e=13.6*(1/(nf*nf)-1/(ni*ni)); return <Card title="Photon from Transition" explanation="Energy difference between levels becomes photon energy." insight="Emission requires ni greater than nf." ask="Balmer/Lyman transition numericals."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="n initial" value={ni} min={2} max={8} onChange={setNi}/><Slider label="n final" value={nf} min={1} max={Math.max(1,ni-1)} onChange={setNf}/><FormulaBox title="Output">E = {fmt(Math.max(0,e))} eV</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="energy-spectrum"/></div></div></Card>}
function Rydberg(){const[ni,setNi]=useState(3),[nf,setNf]=useState(2); const inv=1.097e7*(1/(nf*nf)-1/(ni*ni)); return <Card title="Rydberg Formula" explanation="Hydrogen spectral lines follow inverse wavelength formula." insight="Final level decides series name." ask="Lyman, Balmer and Paschen identification."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="n initial" value={ni} min={2} max={8} onChange={setNi}/><Slider label="n final" value={nf} min={1} max={Math.max(1,ni-1)} onChange={setNf}/><FormulaBox title="Output">1/lambda = {fmt(Math.max(0,inv))} m^-1</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="rydberg"/></div></div></Card>}
function SeriesLimit(){return <Card title="Spectral Series Visual" explanation="Lyman ends at n=1, Balmer at n=2 and Paschen at n=3." insight="Series limit happens when initial level tends to infinity." ask="NCERT series identification."><div className="visual-panel"><DiagramRenderer type="spectrum-lines"/></div></Card>}
function Ionization(){const[n,setN]=useState(2); const e=13.6/(n*n); return <Card title="Ionization Energy from Level n" explanation="Energy needed to remove electron from level n is 13.6/n^2 eV." insight="Ground-state hydrogen needs 13.6 eV." ask="Ionization and excitation energy."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="n" value={n} min={1} max={8} onChange={setN}/><FormulaBox title="Output">E_ion = {fmt(e)} eV</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="energy-level"/></div></div></Card>}
function AngularMomentum(){const[n,setN]=useState(3); return <Card title="Bohr Quantization" explanation="Allowed orbits satisfy mvr = nh/2pi." insight="Quantization explains discrete spectra." ask="Postulate and formula recall."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><Slider label="n" value={n} min={1} max={8} onChange={setN}/><FormulaBox title="Output">L = {n} h/2pi</FormulaBox></div><div className="visual-panel"><DiagramRenderer type="bohr-orbit"/></div></div></Card>}
function SpectrumLines(){return <Card title="Line Spectrum Dashboard" explanation="Discrete spectral lines arise from transitions between discrete energy levels." insight="Atoms emit/absorb only specific photon energies." ask="Conceptual basis of Bohr model."><div className="visual-panel"><DiagramRenderer type="spectrum-lines"/></div></Card>}
